=== spcnz/xml/PortalPoverenika/src/main/resources/xsd/izvestaj.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.izvestaj.com" xmlns="http://www.izvestaj.com">
    <xs:element name="IzvestajRoot">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Izvestaj" type="TIzvestaj"> </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TIzvestaj">
        <xs:sequence>
            <xs:element name="FizickoLice">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="BrojZahteva" type="xs:int"/>
                        <xs:element name="BrojOdbijenihZahteva" type="xs:int"/>
                        <xs:element name="BrojZalbiOdluka" type="xs:int"/>
                        <xs:element name="BrojZalbiCutanje" type="xs:int"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="PravnoLice">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="BrojZahteva" type="xs:int"/>
                        <xs:element name="BrojOdbijenihZahteva" type="xs:int"/>
                        <xs:element name="BrojZalbiOdluka" type="xs:int"/>
                        <xs:element name="BrojZalbiCutanje" type="xs:int"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ReportList">
        <xs:sequence>
            <xs:any maxOccurs="unbounded" minOccurs="0" processContents="skip"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TResponse">
        <xs:sequence>
            <xs:element name="status">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="SUCCESS"/>
                        <xs:enumeration value="FAILED"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== spcnz/xml/PortalPoverenika/src/main/resources/xml/zalbanaodluku.xml
<?xml-stylesheet type="text/xsl" href="../xsl/grddl.xsl"?>
<IzvestajRoot 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns="http://www.izvestaj.com"
    xsi:schemaLocation="http://www.izvestaj.com ../xsd/izvestaj.xsd"
    
    datum="2021-02-03" about="http://izvestaji/20210203230315" 
    property="http://www.tim21.com/predicate/year" id="20210203230315" content="2021" 
    >
    <Izvestaj>
        <FizickoLice>
            <BrojZahteva>101</BrojZahteva>
            <BrojOdbijenihZahteva>230</BrojOdbijenihZahteva>
            <BrojZalbiOdluka>3</BrojZalbiOdluka>
            <BrojZalbiCutanje>1</BrojZalbiCutanje>
        </FizickoLice>
        <PravnoLice>
            <BrojZahteva>0</BrojZahteva>
            <BrojOdbijenihZahteva>0</BrojOdbijenihZahteva>
            <BrojZalbiOdluka>1</BrojZalbiOdluka>
            <BrojZalbiCutanje>0</BrojZalbiCutanje>
        </PravnoLice>
    </Izvestaj>
</IzvestajRoot>
